# ~/.config/starship.toml

add_newline = true # keeps things clean

# Directory module
[directory]
truncation_length = 1
home_symbol = "⌂"     # Unicode home symbol
style = "bold cyan"


# Time
[time]
disabled = false
time_format = "%H:%M"
format = "🕒 [$time]($style) "

# Prompt symbol
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
